--- 
- name: variable introspection demo 
  hosts: localhost 
  gather_facts: false 
 
  tasks: 
    - name: do a thing 
      ansible.builtin.uri: 
        url: https://derpops.bike 
      register: derpops 
 
    - name: show derpops 
      ansible.builtin.debug: 
        msg: "derpops value is {{ derpops }}" 

