---
- name: task inclusion
  hosts: localhost
  gather_facts: false

  tasks:
  - ansible.builtin.include: more-tasks.yaml
    vars:
      data: first
    tags: first

  - ansible.builtin.include: more-tasks.yaml
    vars:
      data: second
    tags: second
