--- 
- name: included task 1 
  ansible.builtin.debug: 
    msg: "I am the first included task with {{ item }}"  
- name: included task 2 
  ansible.builtin.debug: 
    msg: "I am the second included task with {{ item }}" 
