---
- name: error handling
  hosts: all
  gather_facts: false

  tasks:
  - name: delete branch bad
    ansible.builtin.command: git branch -D badfeature
    args:
      chdir: /srv/app

  - name: important task
    ansible.builtin.debug:
      msg: It is important we attempt this task!
